//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamodo {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gamodo.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the function name ähnelt.
        /// </summary>
        internal static string addFunctionDescription {
            get {
                return ResourceManager.GetString("addFunctionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the condition expression ähnelt.
        /// </summary>
        internal static string addIfElseDescription {
            get {
                return ResourceManager.GetString("addIfElseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Classes ähnelt.
        /// </summary>
        internal static string css_class {
            get {
                return ResourceManager.GetString("css_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elements ähnelt.
        /// </summary>
        internal static string css_element {
            get {
                return ResourceManager.GetString("css_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID&apos;s ähnelt.
        /// </summary>
        internal static string css_ids {
            get {
                return ResourceManager.GetString("css_ids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document ähnelt.
        /// </summary>
        internal static string defaultFileName {
            get {
                return ResourceManager.GetString("defaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die deprecated ähnelt.
        /// </summary>
        internal static string deprecated {
            get {
                return ResourceManager.GetString("deprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press [Tab] to go to this position ähnelt.
        /// </summary>
        internal static string EndMarkerToolTip {
            get {
                return ResourceManager.GetString("EndMarkerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press [Tab] to switch between the markers ähnelt.
        /// </summary>
        internal static string expressionTooltip {
            get {
                return ResourceManager.GetString("expressionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file you want to open &quot;{0}&quot; dont exist ähnelt.
        /// </summary>
        internal static string fileDontExist {
            get {
                return ResourceManager.GetString("fileDontExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file you are want to open &quot;%s&quot; don&apos;t exist ähnelt.
        /// </summary>
        internal static string fileDontExists {
            get {
                return ResourceManager.GetString("fileDontExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All files (*.*)|*.* ähnelt.
        /// </summary>
        internal static string filterAll {
            get {
                return ResourceManager.GetString("filterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSS files (*.css)|*.css ähnelt.
        /// </summary>
        internal static string filterCSS {
            get {
                return ResourceManager.GetString("filterCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HTML files (*.htm;*.html;*.xhtml;*.shtml)|*.htm;*.html;*.xhtml;*.shtml ähnelt.
        /// </summary>
        internal static string filterHTML {
            get {
                return ResourceManager.GetString("filterHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JavaScript files (*.js)|*.js ähnelt.
        /// </summary>
        internal static string filterJS {
            get {
                return ResourceManager.GetString("filterJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PHP files (*.php;*.phps;*.php3;*.php4)|*.php;*.phps;*.php3;*.php4 ähnelt.
        /// </summary>
        internal static string filterPHP {
            get {
                return ResourceManager.GetString("filterPHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Web files|*.php;*.phps;*.php3;*.php4;*.htm;*.html;*.xhtml;*.shtml;*.css;*.js ähnelt.
        /// </summary>
        internal static string filterWeb {
            get {
                return ResourceManager.GetString("filterWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment ähnelt.
        /// </summary>
        internal static string FoldTextComment {
            get {
                return ResourceManager.GetString("FoldTextComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unfinished Region ähnelt.
        /// </summary>
        internal static string FoldTextUnfinishedRegion {
            get {
                return ResourceManager.GetString("FoldTextUnfinishedRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the element&apos;s id ähnelt.
        /// </summary>
        internal static string getElementIDDescription {
            get {
                return ResourceManager.GetString("getElementIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The document &quot;{0}&quot; has been changed.{1}Do you wish to save the changes? ähnelt.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startpage ähnelt.
        /// </summary>
        internal static string StartPage {
            get {
                return ResourceManager.GetString("StartPage", resourceCulture);
            }
        }
    }
}
